baseURL = "http://hautzenberger.at/"
languageCode = "en-us"
title = "hautzenberger.at"
theme = "hautzenbergerat"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Photography"
    url = "/tags/photography/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/tags/blog/"
    weight = 3
  [[menu.main]]
    name = "Food"
    url = "/tags/food/"
    weight = 4
  [[menu.main]]
    name = "About me"
    url = "/me"
    weight = 5
